/**
 * Extra names that should link to a concept in tap-to-define text (titles are linked automatically).
 * All-caps acronyms (≤5 chars) match case-sensitively so "FIRE" doesn't catch "fire".
 */
export const GLOSSARY_ALIASES: Record<string, string[]> = {
  budget: ['budgeting', 'budgets'],
  'rule-50-30-20': ['50/30/20'],
  'zero-based-budget': ['zero-based'],
  'lifestyle-inflation': ['lifestyle creep'],
  'sinking-fund': ['sinking funds'],
  'savings-rate': ['savings rates'],
  'emergency-fund': ['emergency funds', 'starter emergency fund'],
  hysa: ['HYSA', 'high-yield savings', 'high-yield savings account', 'high-yield savings accounts'],
  'money-market-fund': ['money market fund', 'money market funds'],
  apr: ['APRs'],
  'high-interest-debt': ['high-interest debt'],
  'debt-avalanche': ['avalanche'],
  'debt-snowball': ['snowball'],
  'minimum-payment-trap': ['minimum payment', 'minimum payments'],
  'student-loans': ['student loan', 'PSLF'],
  mortgage: ['mortgages', 'PMI', 'PITI'],
  amortization: ['amortizing', 'amortized'],
  'credit-score': ['credit scores', 'FICO'],
  'credit-utilization': ['utilization'],
  'credit-report': ['credit reports', 'credit freeze'],
  'prime-directive': ['Prime Directive'],
  '401k': ['401(k)', '401k', '401(k)s', '403(b)', '457(b)'],
  'employer-match': ['employer match', 'the match'],
  vesting: ['vest', 'vested', 'vests'],
  'traditional-vs-roth': ['Roth vs Traditional'],
  'roth-ira': ['Roth IRA', 'Roth IRAs'],
  'traditional-ira': ['Traditional IRA', 'Traditional IRAs'],
  'backdoor-roth': ['backdoor Roth', 'pro-rata rule'],
  hsa: ['HSA', 'HSAs', 'health savings account'],
  'taxable-brokerage': ['taxable account', 'taxable accounts', 'brokerage account'],
  '529-plan': ['529', '529 plans'],
  rollover: ['rollovers', 'direct rollover'],
  'marginal-tax-rate': ['marginal rate', 'tax bracket', 'tax brackets'],
  'effective-tax-rate': ['effective rate'],
  'standard-deduction': ['itemize', 'itemizing'],
  'capital-gains-tax': ['capital gains', 'long-term capital gains', 'short-term capital gains'],
  'tax-loss-harvesting': ['wash sale', 'harvesting losses'],
  'compound-interest': ['compounding', 'compound growth', 'Rule of 72'],
  inflation: ['real return', 'real returns'],
  stocks: ['stock market'],
  bonds: ['bond fund', 'bond funds', 'duration'],
  'risk-and-return': ['risk and return'],
  diversification: ['diversify', 'diversified'],
  'index-fund': ['index funds', 'index investing'],
  'expense-ratio': ['expense ratios'],
  'etf-vs-mutual-fund': ['ETF', 'ETFs', 'mutual fund', 'mutual funds'],
  'total-stock-market': ['total stock market', 'total market'],
  'international-stocks': ['international stocks', 'international stock'],
  'active-vs-passive': ['active funds', 'active management', 'passive investing'],
  'market-timing': ['timing the market', 'time the market'],
  'dollar-cost-averaging': ['dollar-cost averaging', 'DCA', 'lump sum', 'lump-sum'],
  volatility: ['drawdown', 'drawdowns', 'volatile'],
  'bogleheads-philosophy': ['Bogleheads', 'Boglehead', 'John Bogle', 'Jack Bogle'],
  'three-fund-portfolio': ['three-fund', 'three-fund portfolios'],
  'asset-allocation': ['allocation'],
  'age-in-bonds': ['age in bonds'],
  rebalancing: ['rebalance', 'rebalanced'],
  'target-date-fund': ['target-date fund', 'target-date funds', 'target-date'],
  'asset-location': ['asset location', 'tax-efficient fund placement'],
  'stay-the-course': ['stay the course'],
  'risk-tolerance': ['risk tolerance'],
  'four-percent-rule': ['4% rule', 'safe withdrawal rate', 'Trinity study'],
  fire: ['FIRE', 'financial independence'],
  'sequence-risk': ['sequence risk', 'sequence of returns'],
  rmd: ['RMD', 'RMDs'],
  'term-life': ['term life', 'term life insurance'],
  'whole-life': ['whole life'],
  hdhp: ['HDHP', 'high-deductible health plan', 'high-deductible health plans'],
  'bogleheads-getting-started': ['start-up kit', 'getting started guide'],
  'investment-policy-statement': ['investment policy statement', 'IPS'],
  'tax-residency': ['nonresident alien', 'nonresident aliens', 'resident alien', 'resident aliens', 'substantial presence test', 'Form 8843', '1040-NR'],
  'fica-exemption': ['FICA', 'FICA-exempt'],
  'tax-treaty': ['tax treaty', 'tax treaties', 'W-8BEN', 'W-9'],
  pfic: ['PFIC', 'PFICs', 'Form 8621'],
  'fbar-fatca': ['FBAR', 'FATCA', 'Form 8938'],
  'us-estate-tax-nra': ['US-situs', 'estate tax'],
  'ucits-etfs': ['UCITS', 'Ireland-domiciled'],
  'currency-risk': ['currency risk', 'home bias'],
}
