import type { Lesson } from '../types'

export const UNITS = [
  { id: 'u1', title: 'Foundations', subtitle: 'Know where your money goes' },
  { id: 'u2', title: 'Debt & Credit', subtitle: 'Stop the bleeding' },
  { id: 'u3', title: 'Accounts & Priorities', subtitle: 'The Prime Directive' },
  { id: 'u4', title: 'Taxes', subtitle: 'Keep more of what you earn' },
  { id: 'u5', title: 'Investing Basics', subtitle: 'Make money work' },
  { id: 'u6', title: 'The Boglehead Way', subtitle: 'Simple, cheap, diversified' },
  { id: 'u7', title: 'Retirement & Protection', subtitle: 'Finish strong' },
]

export const LESSONS: Lesson[] = [
  /* ───────── Unit 1 ───────── */
  {
    id: 'l-budget',
    unit: 'u1',
    title: 'Budget Basics',
    icon: '🧾',
    blurb: 'Give every dollar a job.',
    requires: [],
    conceptIds: ['budget', 'rule-50-30-20', 'zero-based-budget', 'pay-yourself-first'],
    steps: [
      {
        kind: 'read',
        title: 'Step 0 of everything',
        body: 'Every money goal — an emergency fund, debt freedom, retiring someday — runs on **surplus**: money in minus money out.\n\nA **budget** is just a plan for that surplus. You decide *in advance* where each dollar goes, instead of wondering where it went.',
      },
      {
        kind: 'read',
        title: 'Two easy styles',
        body: '**50/30/20** — 50% needs, 30% wants, 20% savings and extra debt payments. Great for starting out.\n\n**Zero-based** — income minus every planned use equals $0. Savings is a line item, so nothing leaks.\n\nEither way, **pay yourself first**: automate savings on payday.',
      },
      { kind: 'widget', widget: 'budget', title: 'Try it: split a paycheck', caption: 'Drag the sliders. Where does your 20% go?' },
      {
        kind: 'mcq',
        q: 'Take-home pay is $3,500/month. Under 50/30/20, how much goes to savings & extra debt?',
        options: ['$350', '$700', '$1,050', '$1,750'],
        answer: 1,
        explain: '20% of $3,500 = $700.',
      },
      {
        kind: 'tf',
        q: 'In a zero-based budget you must spend all your income.',
        answer: false,
        explain: 'Zero means every dollar is *assigned* — saving and investing are assignments too.',
      },
      {
        kind: 'mcq',
        q: 'What\'s the best way to make saving stick?',
        options: ['Save whatever is left at month-end', 'Automate a transfer on payday', 'Save only bonuses', 'Wait until income is higher'],
        answer: 1,
        explain: 'Pay yourself first: automation removes willpower from the equation.',
      },
    ],
  },
  {
    id: 'l-networth',
    unit: 'u1',
    title: 'Net Worth & Savings Rate',
    icon: '📊',
    blurb: 'Your real scoreboard.',
    requires: ['l-budget'],
    conceptIds: ['net-worth', 'savings-rate', 'lifestyle-inflation', 'sinking-fund'],
    steps: [
      {
        kind: 'read',
        title: 'Income isn\'t wealth',
        body: '**Net worth = assets − liabilities.** A $200k earner who spends $200k builds nothing.\n\nYour **savings rate** (saved ÷ earned) is the lever you control most. It grows your portfolio *and* shrinks how much you\'ll need later.',
      },
      {
        kind: 'read',
        title: 'Two quiet enemies (and one tool)',
        body: '**Lifestyle inflation**: every raise becomes a nicer car. Beat it by saving half of each raise.\n\n**"Surprise" costs that aren\'t surprises**: annual insurance, holidays, car repairs. Use **sinking funds** — save a bit monthly for known future bills.',
      },
      {
        kind: 'mcq',
        q: 'Assets $50k, student loans $30k, car loan $8k. Net worth?',
        options: ['$50k', '$20k', '$12k', '−$12k'],
        answer: 2,
        explain: '$50k − ($30k + $8k) = $12k.',
      },
      {
        kind: 'mcq',
        q: 'Your $900 annual car insurance keeps "surprising" you. Best fix?',
        options: ['Put it on a credit card', 'A $75/month sinking fund', 'Use the emergency fund', 'Pay monthly with a fee'],
        answer: 1,
        explain: 'A known, irregular expense belongs in a sinking fund: $900 ÷ 12 = $75.',
      },
      {
        kind: 'tf',
        q: 'Savings rate helps retirement in two ways: more invested AND less spending to replace.',
        answer: true,
        explain: 'That double effect is why savings rate dominates years-to-retirement math.',
      },
    ],
  },
  {
    id: 'l-emergency',
    unit: 'u1',
    title: 'Emergency Fund',
    icon: '🛟',
    blurb: 'Your financial airbag.',
    requires: ['l-networth'],
    conceptIds: ['emergency-fund', 'hysa', 'money-market-fund'],
    steps: [
      {
        kind: 'read',
        title: 'Two stages',
        body: 'The r/personalfinance flow builds the emergency fund in **two stages**:\n\n1. **Starter fund** (~$1,000 or 1 month of expenses) — so surprises don\'t land on a credit card.\n2. **Full fund: 3–6 months of *essential* expenses** — after high-interest debt is gone.\n\nMore if your income is irregular or others depend on you.',
      },
      {
        kind: 'read',
        title: 'Where to keep it',
        body: 'Safe and liquid. A **high-yield savings account** (FDIC-insured) or a **money market fund**.\n\nNot stocks: recessions bring both job losses *and* market crashes — the worst time to be forced to sell.',
      },
      {
        kind: 'mcq',
        q: 'Essential expenses are $2,500/month. A 4-month emergency fund is…',
        options: ['$2,500', '$7,500', '$10,000', '$15,000'],
        answer: 2,
        explain: '4 × $2,500 = $10,000.',
      },
      {
        kind: 'tf',
        q: 'An emergency fund should be invested in an S&P 500 index fund for higher returns.',
        answer: false,
        explain: 'Emergencies and crashes often arrive together. The fund\'s job is certainty, not return.',
      },
      {
        kind: 'mcq',
        q: 'Emergency fund size should be based on…',
        options: ['Gross income', 'Take-home pay', 'Essential expenses', 'Net worth'],
        answer: 2,
        explain: 'It covers what you\'d *need* to pay if income stopped.',
      },
    ],
  },

  /* ───────── Unit 2 ───────── */
  {
    id: 'l-interest-debt',
    unit: 'u2',
    title: 'The Cost of Debt',
    icon: '🔥',
    blurb: 'Why 24% APR is an emergency.',
    requires: ['l-emergency'],
    conceptIds: ['apr', 'high-interest-debt', 'minimum-payment-trap'],
    steps: [
      {
        kind: 'read',
        title: 'A guaranteed return',
        body: 'Paying off a card charging **24% APR** earns you a *guaranteed, tax-free 24%*. No investment reliably does that.\n\nr/personalfinance treats debt above **~10%** as high-interest: attack it right after grabbing your employer match.',
      },
      {
        kind: 'read',
        title: 'The minimum payment trap',
        body: 'Card minimums are mostly interest. On a large balance, paying only the minimum can take **decades** and cost more than what you bought.\n\nLow-interest debt (under ~4%) is different — paying it on schedule while investing is usually fine.',
      },
      {
        kind: 'mcq',
        q: 'Which should usually be paid off before investing beyond the match?',
        options: ['3% car loan', '22% credit card', '3.5% mortgage', '4% federal student loan'],
        answer: 1,
        explain: '22% is well above the ~10% high-interest line.',
      },
      {
        kind: 'tf',
        q: 'Paying only the credit card minimum is a reasonable long-term plan.',
        answer: false,
        explain: 'Most of the minimum is interest, so the balance barely moves.',
      },
    ],
  },
  {
    id: 'l-payoff',
    unit: 'u2',
    title: 'Avalanche vs Snowball',
    icon: '❄️',
    blurb: 'Two ways to crush debt.',
    requires: ['l-interest-debt'],
    conceptIds: ['debt-avalanche', 'debt-snowball', 'student-loans'],
    steps: [
      {
        kind: 'read',
        title: 'Same start, different target',
        body: 'Both methods: **pay every minimum**, then throw all extra money at one target.\n\n- **Avalanche** → highest *interest rate* first. Least interest paid.\n- **Snowball** → smallest *balance* first. Quick wins for motivation.\n\nThe best plan is the one you\'ll stick to.',
      },
      { kind: 'widget', widget: 'debt', title: 'Race them', caption: 'Change the budget and watch the interest difference.' },
      {
        kind: 'mcq',
        q: 'Debts: $900 at 19%, $4,000 at 26%, $7,000 at 6%. Snowball targets…',
        options: ['$900 at 19%', '$4,000 at 26%', '$7,000 at 6%', 'All equally'],
        answer: 0,
        explain: 'Snowball goes smallest balance first.',
      },
      {
        kind: 'mcq',
        q: 'Same debts — avalanche targets…',
        options: ['$900 at 19%', '$4,000 at 26%', '$7,000 at 6%', 'All equally'],
        answer: 1,
        explain: 'Avalanche goes highest rate first: 26%.',
      },
      {
        kind: 'tf',
        q: 'Refinancing federal student loans into a private loan keeps access to PSLF.',
        answer: false,
        explain: 'Private refinancing gives up federal protections like PSLF and income-driven repayment.',
      },
    ],
  },
  {
    id: 'l-credit',
    unit: 'u2',
    title: 'Credit Scores',
    icon: '💳',
    blurb: 'The number lenders judge you by.',
    requires: ['l-interest-debt'],
    conceptIds: ['credit-score', 'credit-utilization', 'credit-report'],
    steps: [
      {
        kind: 'read',
        title: 'What moves the score',
        body: 'FICO (300–850) weights roughly:\n\n- **Payment history ~35%** → never miss; set autopay for the minimum\n- **Amounts owed ~30%** → mostly *utilization* (balances ÷ limits)\n- Length of history ~15%, new credit ~10%, mix ~10%',
      },
      {
        kind: 'read',
        title: 'Protect yourself',
        body: 'Pull free reports at **AnnualCreditReport.com** and dispute errors. A **credit freeze** at all three bureaus is free, doesn\'t hurt your score, and blocks most new-account fraud.',
      },
      {
        kind: 'mcq',
        q: 'Balances $600 + $900, limits $2,000 + $3,000. Utilization?',
        options: ['15%', '30%', '45%', '60%'],
        answer: 1,
        explain: '$1,500 ÷ $5,000 = 30%.',
      },
      {
        kind: 'tf',
        q: 'Checking your own credit score lowers it.',
        answer: false,
        explain: 'That\'s a soft inquiry. Only hard inquiries (credit applications) have a small effect.',
      },
      {
        kind: 'mcq',
        q: 'The single biggest factor in your FICO score is…',
        options: ['Income', 'Payment history', 'Number of cards', 'Age'],
        answer: 1,
        explain: 'Payment history ≈ 35%. Income isn\'t in the score at all.',
      },
    ],
  },
  {
    id: 'l-loans',
    unit: 'u2',
    title: 'Loans & Mortgages',
    icon: '🏠',
    blurb: 'How amortization really works.',
    requires: ['l-credit'],
    conceptIds: ['amortization', 'mortgage'],
    steps: [
      {
        kind: 'read',
        title: 'Equal payments, shifting mix',
        body: 'An amortizing loan has **equal payments**. Each covers that month\'s interest first; the rest cuts principal. Early on, the balance is big → mostly interest. Later → mostly principal.',
      },
      {
        kind: 'read',
        title: 'Mortgage lingo',
        body: '**PITI** = principal + interest + taxes + insurance. Put down less than **20%** on a conventional loan and you\'ll usually pay **PMI** until you reach ~20% equity.',
      },
      {
        kind: 'mcq',
        q: 'In year 1 of a 30-year mortgage, most of each payment goes to…',
        options: ['Principal', 'Interest', 'PMI', 'Escrow'],
        answer: 1,
        explain: 'Interest is charged on the full balance, which is largest at the start.',
      },
      {
        kind: 'tf',
        q: 'PMI protects the borrower if they lose their job.',
        answer: false,
        explain: 'PMI protects the *lender*, not you.',
      },
    ],
  },

  /* ───────── Unit 3 ───────── */
  {
    id: 'l-prime',
    unit: 'u3',
    title: 'The Prime Directive',
    icon: '🗺️',
    blurb: 'The order of operations for money.',
    requires: ['l-emergency'],
    conceptIds: ['prime-directive'],
    steps: [
      {
        kind: 'read',
        title: 'One flowchart to rule them all',
        body: 'The r/personalfinance flowchart:\n\n1. Budget; pay rent, food, minimums\n2. Starter emergency fund\n3. **Employer match** (free money)\n4. **High-interest debt**\n5. Full emergency fund\n6. **IRA** (+ HSA if eligible)\n7. **Max 401(k)/403(b)**\n8. Taxable investing & other goals',
      },
      {
        kind: 'rank',
        prompt: 'Put these in Prime Directive order (first on top).',
        items: ['Starter emergency fund', 'Get the full employer match', 'Pay off 24% credit card', 'Full 3–6 month emergency fund', 'Fund a Roth IRA', 'Max out the 401(k)', 'Invest in a taxable account'],
        explain: 'Protect → free money → kill expensive debt → full cushion → IRA → max 401(k) → taxable.',
      },
      {
        kind: 'mcq',
        q: 'Why does the match come before paying off a 24% card?',
        options: ['Cards don\'t charge interest monthly', 'A match is an instant 50–100% return', 'Debt payoff isn\'t important', 'Taxes'],
        answer: 1,
        explain: 'An immediate 50–100% beats even 24%.',
      },
    ],
  },
  {
    id: 'm-first-job',
    unit: 'u3',
    title: 'Mission: First Job',
    icon: '🎯',
    blurb: 'Plan Alex\'s first paycheck.',
    requires: ['l-prime'],
    conceptIds: [],
    steps: [
      {
        kind: 'read',
        title: 'Meet Alex',
        body: 'Alex, 25, just started a $60k job. Employer matches **100% up to 4%**. Alex has **$800 in checking**, **$6,000 on a 23% card**, a **4.5% federal student loan**, and no retirement savings.',
      },
      {
        kind: 'rank',
        prompt: 'Order Alex\'s next moves.',
        items: ['Build ~$1,000 starter emergency fund', 'Contribute 4% to get the full match', 'Avalanche the 23% card', 'Grow emergency fund to 3–6 months', 'Open and fund a Roth IRA', 'Increase 401(k) contributions'],
        explain: 'Exactly the Prime Directive. The 4.5% loan is paid on schedule — it\'s not high-interest.',
      },
      {
        kind: 'mcq',
        q: 'How much free money does Alex\'s match give per year?',
        options: ['$1,200', '$2,400', '$4,800', '$6,000'],
        answer: 1,
        explain: '4% of $60,000 = $2,400 from the employer.',
      },
      {
        kind: 'mcq',
        q: 'Alex is in the 12% federal bracket and expects higher income later. Roth or Traditional IRA?',
        options: ['Roth', 'Traditional', 'Neither', 'Doesn\'t matter'],
        answer: 0,
        explain: 'Low tax rate now, likely higher later → pay tax now with Roth.',
      },
    ],
  },
  {
    id: 'l-401k',
    unit: 'u3',
    title: '401(k) & the Match',
    icon: '🏢',
    blurb: 'Free money at work.',
    requires: ['l-prime'],
    conceptIds: ['401k', 'employer-match', 'vesting', 'rollover'],
    steps: [
      {
        kind: 'read',
        title: 'How a 401(k) works',
        body: 'Money comes straight from your paycheck. **Traditional** contributions lower your taxable income today; **Roth 401(k)** contributions are after-tax and grow tax-free. 2026 limit: **$24,500** (under 50).',
      },
      {
        kind: 'read',
        title: 'The match & vesting',
        body: '"50% match up to 6%" means: contribute 6% of salary, employer adds 3%. Your own money is always yours; employer money may **vest** over a few years.\n\nChanging jobs? Do a **direct rollover** to an IRA or the new plan — never cash out.',
      },
      {
        kind: 'mcq',
        q: 'Salary $80k, match "50% up to 6%". You contribute 6%. Employer adds…',
        options: ['$1,200', '$2,400', '$4,800', '$3,000'],
        answer: 1,
        explain: '6% × $80k = $4,800; 50% of that = $2,400.',
      },
      {
        kind: 'tf',
        q: 'If you leave before vesting, you lose your own 401(k) contributions.',
        answer: false,
        explain: 'Only unvested *employer* money can be forfeited.',
      },
      {
        kind: 'mcq',
        q: 'Best move with an old 401(k) when changing jobs?',
        options: ['Cash it out', 'Direct rollover to an IRA or new plan', 'Indirect rollover by check', 'Ignore it forever'],
        answer: 1,
        explain: 'A direct rollover avoids withholding, taxes and penalties.',
      },
    ],
  },
  {
    id: 'l-roth',
    unit: 'u3',
    title: 'Roth vs Traditional',
    icon: '⚖️',
    blurb: 'Pay tax now or later?',
    requires: ['l-401k'],
    conceptIds: ['traditional-vs-roth', 'roth-ira', 'traditional-ira', 'backdoor-roth'],
    steps: [
      {
        kind: 'read',
        title: 'The key insight',
        body: 'Traditional: deduct now, pay tax later. Roth: pay tax now, withdraw tax-free.\n\nIf your tax rate is **the same** at both times, the results are **identical** (because 100 × 0.78 × 2 = 100 × 2 × 0.78). So it\'s a bet: **higher rate now → Traditional; lower now → Roth.**',
      },
      { kind: 'widget', widget: 'rothTrad', title: 'Prove it', caption: 'Set both tax rates equal and watch the bars tie.' },
      {
        kind: 'read',
        title: 'IRA rules',
        body: '2026 IRA limit: **$7,500** combined. Roth *contributions* can come out anytime penalty-free. Over the Roth income limit? The **backdoor Roth** (nondeductible Traditional → convert) — mind the **pro-rata rule**.',
      },
      {
        kind: 'mcq',
        q: 'A doctor in the 35% bracket expects 22% in retirement. Better choice?',
        options: ['Roth', 'Traditional', 'Same', 'Taxable'],
        answer: 1,
        explain: 'Deduct at 35%, pay 22% later.',
      },
      {
        kind: 'tf',
        q: 'You can withdraw Roth IRA contributions (not earnings) anytime without penalty.',
        answer: true,
        explain: 'Contributions come out first and tax-free.',
      },
    ],
  },
  {
    id: 'l-hsa',
    unit: 'u3',
    title: 'HSA & Other Accounts',
    icon: '🩺',
    blurb: 'The triple tax advantage.',
    requires: ['l-roth'],
    conceptIds: ['hsa', 'hdhp', '529-plan', 'taxable-brokerage'],
    steps: [
      {
        kind: 'read',
        title: 'The best account nobody talks about',
        body: 'With an HSA-eligible **HDHP**, an **HSA** is **deductible in, grows tax-free, and comes out tax-free** for medical costs. 2026: $4,400 self / $8,750 family.\n\nPower move: invest it, pay medical bills from cash, keep receipts, reimburse yourself years later.',
      },
      {
        kind: 'read',
        title: 'Two more',
        body: '**529 plan**: tax-free growth for education. Fund your own retirement first — kids can borrow for college, you can\'t borrow for retirement.\n\n**Taxable brokerage**: no limits, no rules — used after tax-advantaged space.',
      },
      {
        kind: 'mcq',
        q: 'What makes the HSA\'s tax treatment unique?',
        options: ['Only tax-free growth', 'Tax-free in, growth, and out (for medical)', 'No limits', 'No health plan requirement'],
        answer: 1,
        explain: 'It\'s the only account with a triple tax advantage.',
      },
      {
        kind: 'tf',
        q: 'Anyone with health insurance can contribute to an HSA.',
        answer: false,
        explain: 'You need HSA-eligible high-deductible coverage.',
      },
    ],
  },

  /* ───────── Unit 4 ───────── */
  {
    id: 'l-brackets',
    unit: 'u4',
    title: 'How Tax Brackets Work',
    icon: '🧮',
    blurb: 'A raise never hurts.',
    requires: ['l-roth'],
    conceptIds: ['marginal-tax-rate', 'effective-tax-rate', 'standard-deduction'],
    steps: [
      {
        kind: 'read',
        title: 'Buckets, not cliffs',
        body: 'Picture buckets: the first bucket of income is taxed at 10%, the next at 12%, then 22%… Only dollars *inside* a bucket get that rate.\n\n**Marginal rate** = rate on your next dollar. **Effective rate** = total tax ÷ income (always lower). The **standard deduction** is a 0% bucket at the very bottom.',
      },
      {
        kind: 'tf',
        q: 'A raise that moves you into the 22% bracket can reduce your take-home pay.',
        answer: false,
        explain: 'Only the dollars above the threshold are taxed at 22%.',
      },
      {
        kind: 'mcq',
        q: 'Which rate should you use to value a Traditional 401(k) deduction?',
        options: ['Effective', 'Marginal', 'Average of both', 'Capital gains'],
        answer: 1,
        explain: 'Deducted dollars come off the top — they\'d have been taxed at your marginal rate.',
      },
      {
        kind: 'mcq',
        q: 'Itemized deductions total $9,000; the standard deduction is higher. You should…',
        options: ['Itemize', 'Take the standard deduction', 'Do both', 'Skip deductions'],
        answer: 1,
        explain: 'Take the larger of the two.',
      },
    ],
  },
  {
    id: 'l-invest-tax',
    unit: 'u4',
    title: 'Taxes on Investments',
    icon: '🏷️',
    blurb: 'Hold longer, harvest losses.',
    requires: ['l-brackets'],
    conceptIds: ['capital-gains-tax', 'tax-loss-harvesting'],
    steps: [
      {
        kind: 'read',
        title: 'Short vs long term',
        body: 'Sell for a profit in a taxable account → **capital gains tax**. Held **over 1 year** → long-term rates (0/15/20%). One year or less → ordinary income rates.\n\n**Tax-loss harvesting**: sell at a loss, buy something similar (not "substantially identical"), use the loss to offset gains + up to $3,000 of income. Watch the 30-day **wash sale** window.',
      },
      {
        kind: 'mcq',
        q: 'You bought a fund 11 months ago and it\'s up. Selling now means…',
        options: ['Long-term rates', 'Short-term (ordinary) rates', 'No tax', '10% penalty'],
        answer: 1,
        explain: 'You need to hold more than one year for long-term rates.',
      },
      {
        kind: 'tf',
        q: 'Selling a fund at a loss and buying it back 10 days later still lets you claim the loss.',
        answer: false,
        explain: 'That\'s a wash sale — the loss is disallowed.',
      },
    ],
  },

  /* ───────── Unit 5 ───────── */
  {
    id: 'l-compound',
    unit: 'u5',
    title: 'The Magic of Compounding',
    icon: '🌱',
    blurb: 'Time is your superpower.',
    requires: ['l-emergency'],
    conceptIds: ['compound-interest', 'inflation'],
    steps: [
      {
        kind: 'read',
        title: 'Returns on returns',
        body: 'Compounding means your earnings earn too. Growth is exponential, so **time** matters most.\n\n**Rule of 72:** years to double ≈ 72 ÷ return%. At 8%: ~9 years. At 6%: ~12.',
      },
      { kind: 'widget', widget: 'compound', title: 'Play with time', caption: 'Compare starting at 25 vs 35. Watch the gap.' },
      {
        kind: 'read',
        title: 'The silent tax: inflation',
        body: 'Prices rise ~3%/year on average. **Real return ≈ return − inflation.** Cash at 0% loses ~3% of buying power every year.',
      },
      {
        kind: 'mcq',
        q: 'At 6% per year, money doubles in about…',
        options: ['6 years', '10 years', '12 years', '20 years'],
        answer: 2,
        explain: '72 ÷ 6 = 12.',
      },
      {
        kind: 'mcq',
        q: 'Investments earn 7% while inflation is 3%. Real return ≈',
        options: ['10%', '7%', '4%', '2.3%'],
        answer: 2,
        explain: '7% − 3% ≈ 4%.',
      },
    ],
  },
  {
    id: 'l-assets',
    unit: 'u5',
    title: 'Stocks, Bonds & Risk',
    icon: '🎢',
    blurb: 'No free lunch (almost).',
    requires: ['l-compound'],
    conceptIds: ['stocks', 'bonds', 'risk-and-return', 'volatility'],
    steps: [
      {
        kind: 'read',
        title: 'The two building blocks',
        body: '**Stocks** = ownership. Highest long-run expected return, but 30–50% drops happen.\n\n**Bonds** = loans. Lower return, much steadier. When rates rise, existing bond prices fall (longer **duration** → bigger drop).\n\nHigher expected return always comes with higher risk.',
      },
      {
        kind: 'mcq',
        q: 'Interest rates jump 1%. A bond fund with duration 6 will likely…',
        options: ['Rise ~6%', 'Fall ~6%', 'Not change', 'Fall ~1%'],
        answer: 1,
        explain: 'Price change ≈ −duration × rate change.',
      },
      {
        kind: 'tf',
        q: 'A 40% drop in your stock fund is a permanent loss even if you don\'t sell.',
        answer: false,
        explain: 'It becomes permanent only if you sell before recovery.',
      },
      {
        kind: 'mcq',
        q: 'Someone offers "15% guaranteed returns, zero risk". This is…',
        options: ['A great deal', 'A red flag', 'Typical for bonds', 'Typical for index funds'],
        answer: 1,
        explain: 'High return + no risk doesn\'t exist. Walk away.',
      },
    ],
  },
  {
    id: 'l-index',
    unit: 'u5',
    title: 'Index Funds & Costs',
    icon: '🧺',
    blurb: 'Buy the haystack.',
    requires: ['l-assets'],
    conceptIds: ['diversification', 'index-fund', 'expense-ratio', 'active-vs-passive', 'etf-vs-mutual-fund'],
    steps: [
      {
        kind: 'read',
        title: 'Don\'t look for the needle',
        body: '**Diversification** cuts single-company risk without cutting expected return. An **index fund** does it in one purchase — thousands of companies, tiny fee.\n\nMost **active** funds trail their index after costs, and last decade\'s winners rarely repeat.',
      },
      {
        kind: 'read',
        title: 'Costs compound too',
        body: 'An **expense ratio** of 0.04% costs $4 per $10k per year. 1% costs $100 — and you lose the growth on it, every year, for decades.',
      },
      { kind: 'widget', widget: 'fees', title: 'The fee monster', caption: 'Slide the fee from 0.04% to 1%. Where did all that money go?' },
      {
        kind: 'mcq',
        q: 'Why do most active funds underperform index funds over time?',
        options: ['Managers are bad', 'Higher costs on top of an average (market) return', 'Index funds cheat', 'Regulations'],
        answer: 1,
        explain: 'Collectively active investors *are* the market; costs push the average below it.',
      },
      {
        kind: 'tf',
        q: 'For a long-term investor, choosing ETF vs mutual fund matters more than the fund\'s costs.',
        answer: false,
        explain: 'Costs and the underlying index matter far more than the wrapper.',
      },
    ],
  },
  {
    id: 'l-timing',
    unit: 'u5',
    title: 'Time In, Not Timing',
    icon: '⏳',
    blurb: 'Why guessing fails.',
    requires: ['l-index'],
    conceptIds: ['market-timing', 'dollar-cost-averaging'],
    steps: [
      {
        kind: 'read',
        title: 'You\'d have to be right twice',
        body: 'Market timing requires knowing when to get out *and* when to get back in. The best days often come right after the worst — miss a handful and returns crater.\n\nWith a windfall, **lump-sum** investing beats **dollar-cost averaging** about two-thirds of the time. DCA mostly buys peace of mind.',
      },
      {
        kind: 'mcq',
        q: 'You inherit $50k. Historically, which usually ends up ahead?',
        options: ['Lump sum now', 'DCA over 12 months', 'Wait for a crash', 'Keep in cash'],
        answer: 0,
        explain: 'Markets rise more often than they fall, so earlier is usually better.',
      },
      {
        kind: 'tf',
        q: 'Contributing part of every paycheck to your 401(k) is a form of dollar-cost averaging.',
        answer: true,
        explain: 'Fixed amounts at regular intervals — DCA by default.',
      },
    ],
  },

  /* ───────── Unit 6 ───────── */
  {
    id: 'l-boglehead',
    unit: 'u6',
    title: 'The Boglehead Philosophy',
    icon: '🧭',
    blurb: 'Jack Bogle\'s ten rules.',
    requires: ['l-index'],
    conceptIds: ['bogleheads-philosophy', 'stay-the-course'],
    steps: [
      {
        kind: 'read',
        title: 'Ten ideas',
        body: '1. Develop a workable plan\n2. Invest early and often\n3. Never bear too much or too little risk\n4. Diversify\n5. Never try to time the market\n6. Use index funds when possible\n7. Keep costs low\n8. Minimize taxes\n9. Invest with simplicity\n10. **Stay the course**',
      },
      {
        kind: 'read',
        title: 'The behavior gap',
        body: 'Investors often earn *less than the funds they own* — buying after gains, selling after drops. A simple plan you actually stick to beats a clever one you abandon.',
      },
      {
        kind: 'mcq',
        q: 'Markets drop 30% in a month. The Boglehead response is…',
        options: ['Sell everything', 'Stay the course (and maybe rebalance)', 'Switch to gold', 'Stop contributing'],
        answer: 1,
        explain: 'Stick to the plan; rebalancing even buys stocks cheaply.',
      },
      {
        kind: 'tf',
        q: 'Bogleheads try to pick the best-performing fund of the last 5 years.',
        answer: false,
        explain: 'Past winners rarely persist; chasing performance is a classic mistake.',
      },
    ],
  },
  {
    id: 'l-three-fund',
    unit: 'u6',
    title: 'The Three-Fund Portfolio',
    icon: '🥧',
    blurb: 'The whole world in three funds.',
    requires: ['l-boglehead'],
    conceptIds: ['three-fund-portfolio', 'total-stock-market', 'international-stocks', 'target-date-fund'],
    steps: [
      {
        kind: 'read',
        title: 'Three funds, thousands of holdings',
        body: '1. **US total stock market**\n2. **International total stock market**\n3. **US total bond market**\n\nYou choose the percentages. Many use 20–40% of stocks in international.\n\nWant zero maintenance? A **target-date fund** is basically a three/four-fund portfolio in a box that gets more conservative automatically.',
      },
      {
        kind: 'mcq',
        q: 'Which is NOT one of the classic three funds?',
        options: ['Total US stock', 'Total international stock', 'Total US bond', 'Gold ETF'],
        answer: 3,
        explain: 'The classic three are US stock, international stock, and US bonds.',
      },
      {
        kind: 'mcq',
        q: 'A target-date 2065 fund will, over time…',
        options: ['Stay 90% stocks forever', 'Shift toward more bonds', 'Shift toward more stocks', 'Only hold cash'],
        answer: 1,
        explain: 'That\'s its glide path.',
      },
    ],
  },
  {
    id: 'l-allocation',
    unit: 'u6',
    title: 'Allocation & Rebalancing',
    icon: '🎚️',
    blurb: 'Set your risk dial.',
    requires: ['l-three-fund'],
    conceptIds: ['asset-allocation', 'age-in-bonds', 'risk-tolerance', 'rebalancing'],
    steps: [
      {
        kind: 'read',
        title: 'The biggest decision',
        body: '**Asset allocation** (stocks vs bonds) drives most of your risk and return. Base it on your need, ability, and willingness to take risk. Starting heuristic: **"age in bonds"** (or age − 10/20 for more aggression).\n\nGut check: *if stocks fell 50%, would I sell?*',
      },
      {
        kind: 'read',
        title: 'Rebalancing',
        body: 'Markets drift your mix. **Rebalance** once a year or when something is **5 points off target**. Do it with new contributions or inside tax-advantaged accounts to avoid taxes.',
      },
      {
        kind: 'mcq',
        q: 'Target 70/30. After a boom you\'re 80/20. Rebalancing means…',
        options: ['Buy more stocks', 'Sell stocks / buy bonds back to 70/30', 'Do nothing ever', 'Go 100% stocks'],
        answer: 1,
        explain: 'Return to target: trim the winner, top up the laggard.',
      },
      {
        kind: 'mcq',
        q: '"Age minus 10 in bonds" for a 35-year-old is…',
        options: ['35% bonds', '25% bonds', '10% bonds', '45% bonds'],
        answer: 1,
        explain: '35 − 10 = 25% bonds.',
      },
    ],
  },
  {
    id: 'l-location',
    unit: 'u6',
    title: 'Asset Location',
    icon: '📍',
    blurb: 'Right fund, right account.',
    requires: ['l-allocation', 'l-invest-tax'],
    conceptIds: ['asset-location'],
    steps: [
      {
        kind: 'read',
        title: 'Same mix, less tax',
        body: '**Allocation** = what you hold. **Location** = where.\n\nPut tax-*inefficient* assets (bonds, REITs) in 401(k)/IRA. Keep tax-*efficient* broad stock index funds in taxable. Roth space is great for the highest-growth assets.',
      },
      {
        kind: 'rank',
        prompt: 'Rank from BEST to WORST fit for a taxable account.',
        items: ['Total US stock index ETF', 'Total international stock index', 'Actively managed stock fund', 'Taxable bond fund'],
        explain: 'Broad stock index funds are most tax-efficient; bonds throw off ordinary-income interest.',
      },
      {
        kind: 'tf',
        q: 'Bond funds are generally better held in tax-advantaged accounts.',
        answer: true,
        explain: 'Their interest is taxed as ordinary income each year in taxable.',
      },
    ],
  },
  {
    id: 'm-portfolio',
    unit: 'u6',
    title: 'Mission: Build the Portfolio',
    icon: '🎯',
    blurb: 'Help Sam invest $100k.',
    requires: ['l-location'],
    conceptIds: [],
    steps: [
      {
        kind: 'read',
        title: 'Meet Sam',
        body: 'Sam, 38, wants **75/25 stocks/bonds** with 30% of stocks international. Accounts: **$60k 401(k)** (has a total bond index and an S&P 500 fund), **$40k taxable**.',
      },
      {
        kind: 'mcq',
        q: 'Where should Sam\'s $25k of bonds live?',
        options: ['Taxable', '401(k)', 'Split evenly', 'Nowhere — skip bonds'],
        answer: 1,
        explain: 'Bonds are tax-inefficient → tax-advantaged space.',
      },
      {
        kind: 'mcq',
        q: 'Sam\'s stock total is $75k. International target is…',
        options: ['$22.5k', '$30k', '$25k', '$15k'],
        answer: 0,
        explain: '30% of $75k = $22.5k.',
      },
      {
        kind: 'mcq',
        q: 'Best choice for the international fund given the accounts?',
        options: ['Total international index in taxable', 'Active international fund in 401(k)', 'Skip international', 'International bond fund'],
        answer: 0,
        explain: 'The 401(k) has no intl option; a broad intl index is tax-efficient and can claim the foreign tax credit in taxable.',
      },
    ],
  },

  /* ───────── Unit 7 ───────── */
  {
    id: 'l-fire',
    unit: 'u7',
    title: 'The 4% Rule & FIRE',
    icon: '🔥',
    blurb: 'How much is enough?',
    requires: ['l-allocation'],
    conceptIds: ['four-percent-rule', 'fire', 'sequence-risk'],
    steps: [
      {
        kind: 'read',
        title: '25× expenses',
        body: 'Withdraw **4%** of your starting portfolio, raise it with inflation each year — historically that lasted **30 years** in nearly every US scenario. Flip it: you need about **25× annual spending**.\n\nEarly retirees (40+ year horizons) often plan on 3–3.5%.',
      },
      { kind: 'widget', widget: 'fire', title: 'Your FI timeline', caption: 'Savings rate is the big lever. Try 10%, 25%, 50%.' },
      {
        kind: 'read',
        title: 'Sequence risk',
        body: 'A crash in *year 1* of retirement hurts far more than the same crash in year 20 — withdrawals lock in losses. Bonds and flexible spending help.',
      },
      {
        kind: 'mcq',
        q: 'You spend $48k/year. 4% rule target?',
        options: ['$480k', '$1.2M', '$1.92M', '$960k'],
        answer: 1,
        explain: '$48k × 25 = $1.2M.',
      },
      {
        kind: 'tf',
        q: 'Savings rate matters more than investment return for how fast you reach FI.',
        answer: true,
        explain: 'Within reasonable return ranges, savings rate dominates the timeline.',
      },
    ],
  },
  {
    id: 'l-late',
    unit: 'u7',
    title: 'RMDs & Social Security',
    icon: '🏛️',
    blurb: 'The rules at the finish line.',
    requires: ['l-fire'],
    conceptIds: ['rmd', 'social-security'],
    steps: [
      {
        kind: 'read',
        title: 'Two late-game rules',
        body: '**RMDs**: from age 73 (75 if born 1960+), pre-tax accounts force yearly withdrawals. Roth IRAs don\'t (for the original owner).\n\n**Social Security**: based on your top 35 earning years. Claim at 62 (reduced) up to 70 (~8%/year bigger after full retirement age).',
      },
      {
        kind: 'mcq',
        q: 'Which account has no RMDs for its original owner?',
        options: ['Traditional IRA', 'Traditional 401(k)', 'Roth IRA', 'SEP IRA'],
        answer: 2,
        explain: 'Roth IRAs skip RMDs during the owner\'s lifetime.',
      },
      {
        kind: 'tf',
        q: 'Delaying Social Security from full retirement age to 70 increases benefits about 8% per year.',
        answer: true,
        explain: 'Delayed retirement credits ≈ 8%/year.',
      },
    ],
  },
  {
    id: 'l-insurance',
    unit: 'u7',
    title: 'Insurance That Matters',
    icon: '🛡️',
    blurb: 'Protect the plan.',
    requires: ['l-hsa'],
    conceptIds: ['term-life', 'whole-life', 'disability-insurance'],
    steps: [
      {
        kind: 'read',
        title: 'Insure catastrophes, not inconveniences',
        body: '**Term life**: cheap; needed if others depend on your income (~10–12× income).\n\n**Whole life**: expensive insurance + mediocre investment. The consensus: **buy term and invest the difference.**\n\n**Disability**: for young workers, future earnings are the biggest asset — long-term disability protects it.',
      },
      {
        kind: 'mcq',
        q: 'Single 24-year-old, no dependents. Life insurance need?',
        options: ['Large whole life policy', 'Probably none (or small employer policy)', '$2M term', 'Universal life'],
        answer: 1,
        explain: 'No one relies on the income, so there\'s little to insure.',
      },
      {
        kind: 'tf',
        q: 'Whole life insurance is generally recommended as a retirement investment.',
        answer: false,
        explain: 'High costs and low returns; term + index funds usually wins.',
      },
    ],
  },
]

export const LESSON_BY_ID = Object.fromEntries(LESSONS.map((l) => [l.id, l]))
